
- shell:
    # Update system
  - sudo pacman -Syu --noconfirm

    # Install yay
  - command -v yay > /dev/null || (sudo pacman -S --noconfirm --needed base-devel && mkdir -p ~/dev/external && cd ~/dev/external && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm && cd .. && rm -rf yay)

    # Install flatpak
  - sudo pacman -S --noconfirm --needed flatpak
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  
    # Install graphics drivers
  - sudo pacman -S --noconfirm --needed libva-mesa-driver libva-utils mesa vulkan-radeon

    # Install general utils
  - sudo pacman -S --noconfirm --needed  smartmontools xdg-utils gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-plugins-base gst-plugins-base-libs gst-libav ddcutil wl-clipboard gnome-keyring libsecret wev unzip wtype reflector brightnessctl sof-firmware acpi fwupd

    # Install arch utils (gui)
  - sudo pacman -S --noconfirm --needed blueman pavucontrol noto-fonts noto-fonts-cjk noto-fonts-emoji noto-fonts-extra

    # Nautilus
  - sudo pacman -S --noconfirm --needed nautilus nautilus-python gvfs-smb gvfs-dnssd gvfs-mtp sushi udiskie

    # AUR
  - yay -S --noconfirm --needed --answerdiff None --answerclean None downgrade clipse

