
- shell:
    # Update system
  - sudo pacman -Syu --noconfirm

    # Ensure Downloads dir exists
  - mkdir -p ~/Downloads

    # Install yay
  - command -v yay > /dev/null || (sudo pacman -S --noconfirm --needed base-devel && git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si --noconfirm && cd .. && rm -rf yay)

    # Install flatpak
  - sudo pacman -S --noconfirm --needed flatpak
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  
    # Install graphics drivers
  - sudo pacman -S --noconfirm --needed libva-mesa-driver libva-utils mesa vulkan-radeon

    # Install arch utils
  - sudo pacman -S --noconfirm --needed iwd wireless_tools wpa_supplicant smartmontools xdg-utils gst-plugins-good gst-plugins-bad gst-plugins-ugly gst-libav inetutils iwd ddcutil

    # Install arch utils (gui)
  - sudo pacman -S --noconfirm --needed virt-manager blueman pavucontrols networkmanager network-manager-applet nm-connection-editor noto-fonts-emoji

    # Nautilus
  - sudo pacman -S --noconfirm --needed nautilus nautilus-python gvfs-smb sushi udiskie

    # AUR
  - yay -S --noconfirm --needed --answerdiff None --answerclean None downgrade clipse
