
- link:
    ~/.config/AutoRaise/config: mac/autoraise/config

- shell:
  - brew tap dimentium/autoraise
  - brew install autoraise --with-dalternative_task_switcher
  - brew services start autoraise
