
- shell:
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed perl-curses perl-term-animation cava cmatrix cowsay ponysay countryfetch lolcat fortune-mod sl espeak-ng toilet nyancat; fi

