
- shell:
  - sudo pacman -S --noconfirm --needed papirus-icon-theme
  - mkdir -p ~/dev/external && git clone https://github.com/vinceliuice/Colloid-icon-theme.git ~/dev/external/Colloid-icon-theme
  - cd ~/dev/external/Colloid-icon-theme && ./install.sh -s catppuccin -t yellow -b
  - cd ~/dev/external && rm -rf Colloid-icon-theme
  - gsettings set org.gnome.desktop.interface icon-theme "Colloid-Yellow-Catppuccin-Dark"
