
- shell:
  - sudo pacman -S --noconfirm --needed keyd
  - sudo rm -rf /etc/keyd/default.conf
  - mkdir -p /etc/keyd && sudo cp keyd/default.conf /etc/keyd/
  - sudo systemctl is-enabled keyd.service &>/dev/null && sudo keyd reload || sudo systemctl enable --now keyd.service

