
- shell:
  - sudo pacman -R --noconfirm iptables 2> /dev/null || true #Since we're about to install iptables-nft
  - sudo pacman -S --noconfirm --needed nftables iptables-nft networkmanager nm-connection-editor iwd inetutils
  - sudo pacman -S --noconfirm --needed network-manager-applet #eventually remove?

  # wifi
  - sudo systemctl enable iwd
  - sudo systemctl disable wpa_supplicant
  - sudo systemctl mask wpa_supplicant

  # systemd-resolvd (dns)
  - sudo systemctl enable --now systemd-resolved
  - sudo ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf

  # Networkmanager conf
  - sudo mkdir -p /etc/NetworkManager/conf.d
  - sudo rm -f /etc/NetworkManager/conf.d/00-networkmanager.conf
  - sudo cp network/networkmanager.conf /etc/NetworkManager/conf.d/00-networkmanager.conf
  - sudo systemctl restart NetworkManager
