
- link:
    ~/.config/onlyoffice: apps/onlyoffice/theme.json

- shell:
  - if [ "$(uname)" = "Linux" ]; then flatpak install --noninteractive flathub org.onlyoffice.desktopeditors; else brew install --cask onlyoffice; fi
