
- link:
    /etc/sddm.conf: sddm/sddm.conf

- shell:
  - sudo rm -rf /usr/share/sddm/themes/catppuccin-mocha-peach
  - sudo cp -r sddm/catppuccin-mocha-peach /usr/share/sddm/themes/catppuccin-mocha-peach
