
- shell:
  - mkdir -p ~/dev/projects
  - mkdir -p ~/dev/external
  - mkdir -p ~/Downloads

  - sudo pacman -S --noconfirm --needed ttf-jetbrains-mono-nerd tailscale openssh

    # Install GUI packages
  - sudo pacman -S --noconfirm --needed impression audacity gnome-calculator decibels papers loupe showtime switcheroo gnome-calendar libreoffice-fresh blender kdenlive
  - flatpak install --assumeyes --noninteractive flathub org.nickvision.tubeconverter io.gitlab.adhami3310.Footage
  - yay -S --noconfirm --needed --answerdiff None --answerclean None zsh-vi-mode

    # Enable systemd services
  - sudo systemctl enable tailscaled
  - sudo systemctl enable sshd
