
- link:
    ~/.config/nvim: nvim
    ~/.config/hypr:
      path: hypr/*
      glob: true
      exclude: [hypr/uwsm, hypr/hypridle*.conf]

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed tailscale
      yay -S --noconfirm --needed --answerdiff None --answerclean None ripdrag
    elif [[ "$(./sys id)" == "fedora" ]]; then
      sudo dnf install -y tailscale
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      sudo apt install -y tailscale
    elif [[ "$(./sys id)" == "mac" ]]; then
      brew install tailscale
    fi
