
- shell:
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed wget curl ffmpeg 7zip fd ripgrep poppler zoxide imagemagick chafa resvg ncdu fzf trash-cli tldr whois eza jq less bluetui impala yt-dlp gum git-delta gnuplot nmap bind id3v2 bc lazygit; else brew install wget ffmpeg 7zip fd ripgrep poppler zoxide imagemagick ghostscript chafa resvg ncdu fzf trash-cli tlrc eza jq less yt-dlp gum git-delta gnuplot nmap bind id3v2 bc; fi

