
- link:
    ~/.config/tmux/tmux.conf: tmux/tmux.conf
    ~/.local/bin/:
      path: tmux/scripts/*
      glob: true

- shell:
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed tmux; else brew install tmux; fi
