
- link:
    ~/.config/zsh/.zshrc: zsh/zshrc
    ~/.config/zsh/.zshenv: zsh/zshenv
    ~/.config/zsh/.zprofile:
      path: zsh/zprofile-mac
      if: '[ "$(uname)" = "Darwin" ]'
    ~/.zshenv: zsh/zshenv
    ~/.config/zsh/.zshrc-mac:
      path: zsh/zshrc-mac
      if: '[ "$(uname)" = "Darwin" ]'

- shell:
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed zsh; fi
  - if [ "$SHELL" != "$(which zsh)" ]; then chsh -s "$(which zsh)"; fi
