
- link:
    ~/.zshrc: 
      path: zsh/zshrc
      if: '[ "$(uname)" = "Linux" ]' 
    ~/.zshrc:
      path: zsh/zshrc-mac
      if: '[ "$(uname)" = "Darwin" ]'

- shell:
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed zsh; fi
  - if [ "$SHELL" != "$(which zsh)" ]; then chsh -s "$(which zsh)"; fi
