
- link:
    ~/.config/zsh/.zshrc: 
      path: zsh/zshrc
      if: '[ "$(uname)" = "Linux" ]' 
    ~/.config/zsh/.zprofile:
      path: zsh/zprofile-mac
      if: '[ "$(uname)" = "Darwin" ]'
    ~/.zshenv:
      path: zsh/zshenv
- link:
    ~/.config/zsh/.zshrc:
      path: zsh/zshrc-mac
      if: '[ "$(uname)" = "Darwin" ]'

- shell:
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed zsh; fi
  - if [ "$SHELL" != "$(which zsh)" ]; then chsh -s "$(which zsh)"; fi
