
- shell:
  - |
    if ! grep -q "max_parallel_downloads" /etc/dnf/dnf.conf; then
      sudo tee -a /etc/dnf/dnf.conf > /dev/null <<EOF
    max_parallel_downloads=10
    fastestmirror=True
    EOF
    fi

#Todo - Add additional tweaks to dnf conf
