
- link:
    ~/.config/GIMP/3.0/:
      path: apps/gimp/*
      glob: true

- shell:
  - mkdir -p ~/Downloads/Screenshots ~/Downloads/Videos

    # Install GUI packages
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed audacity decibels papers loupe showtime libreoffice-fresh blender kdenlive nextcloud-client gimp resources; else brew install --cask nextcloud; fi
  - if [ "$(uname)" = "Linux" ]; then flatpak install --assumeyes --noninteractive flathub org.nickvision.tubeconverter com.github.PintaProject.Pinta; fi

  # Nautilus
  - if [[ "$(./sys id)" == "arch" ]]; then sudo pacman -S --noconfirm --needed nautilus nautilus-python gvfs-smb gvfs-dnssd gvfs-mtp sushi udiskie; fi
  - |
    if [[ "$(./sys type)" == "Linux" ]]; then
      gsettings set org.gnome.nautilus.icon-view captions "['size', 'none', 'none']"
      gsettings set org.gtk.gtk4.Settings.FileChooser sort-directories-first true
    fi

# Kicked out
#gnome-disk-utility, gnome-power-manager, gnome-calender
#blueman, pavucontrol, gnome-calculator, file-roller
#switcheroo, impression, vesktop, gnucash, typora
# be.alexandervanhee.gradia
