
- link:
    ~/.config/GIMP/3.0/:
      path: apps/gimp/*
      glob: true

- shell:
  - mkdir -p ~/Downloads/Screenshots ~/Downloads/Videos

    # Install GUI packages
  - if [ "$(uname)" = "Linux" ]; then sudo pacman -S --noconfirm --needed audacity decibels papers loupe showtime libreoffice-fresh blender kdenlive nextcloud-client gimp; else brew install --cask moonlight nextcloud; fi
  - if [ "$(uname)" = "Linux" ]; then flatpak install --assumeyes --noninteractive flathub org.nickvision.tubeconverter be.alexandervanhee.gradia io.typora.Typora; fi
    
  # Nautilus
  - if [[ "$(./sys id)" == "arch" ]]; then sudo pacman -S --noconfirm --needed nautilus nautilus-python gvfs-smb gvfs-dnssd gvfs-mtp sushi udiskie; fi
  - if [[ "$(./sys type)" == "Linux" ]]; then gsettings set org.gnome.nautilus.icon-view captions "['size', 'none', 'none']"; fi


# Kicked out
#gnome-disk-utility, gnome-power-manager, gnome-calender
#blueman, pavucontrol, gnome-calculator, file-roller
#switcheroo, impression, vesktop, gnucash
