format = '$all'

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[hostname]
ssh_only=true
format = "[$hostname](bold yellow) in "

[python]
format='via [${symbol}(\($virtualenv\) )]($style)'
