always_show_default = false

engines_as_actions = false
#if false each engine will have an entry, if true it will show a "search" entry and you must use alt+j to do anything

[[entries]]
default = true
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[entries]]
name = "YouTube"
prefix = "@yt"
url = "https://www.youtube.com/results?search_query=%TERM%"

[[entries]]
name = "Arch Packages"
prefix = "@pkgs"
url = "https://archlinux.org/packages/?q=%TERM%"

[[entries]]
name = "AUR"
prefix = "@aur"
url = "https://aur.archlinux.org/packages?O=0&K=%TERM%"

[[entries]]
name = "Flathub"
prefix = "@flat"
url = "https://flathub.org/apps/search?q=%TERM%"

[[entries]]
name = "Ubuntu Packages"
prefix = "@upkgs"
url = "https://packages.ubuntu.com/%TERM%"
