
- shell:
  # Install flatpak
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed flatpak
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      sudo apt install -y flatpak
    fi
  - flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
