
- link:
    ~/.config/bat: tui/bat

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed bat 
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install bat
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install bat
    fi
  - bat cache --build
