
- link:
    ~/.config/btop: tui/btop

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed btop
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install btop
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install btop
    fi
