
- link:
    ~/.config/fastfetch/config.jsonc:
      path: tui/fastfetch/config.jsonc
      if: '[[ "$(./sys type)" == "Linux" ]]'
- link:
    ~/.config/fastfetch/config.jsonc:
      path: tui/fastfetch/config-mac.jsonc
      if: '[[ "$(./sys type)" == "Darwin" ]]'

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed fastfetch
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      sudo add-apt-repository -y ppa:zhangsongcui3371/fastfetch
      sudo apt update
      sudo apt install -y fastfetch
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install fastfetch
    fi

