
- link:
    ~/.config/nvim: nvim

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed neovim
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      sudo add-apt-repository -y ppa:neovim-ppa/unstable
      sudo apt update
      sudo apt install -y neovim python3-dev python3-pip python3-venv
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install neovim
    fi
