
- link:
    ~/.config/nvim: nvim

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed neovim
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      sudo apt install -y neovim
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install neovim
    fi
