#Neovim + python

- link:
    ~/.config/nvim: nvim
    ~/.editorconfig: nvim/.editorconfig

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed neovim python python-pip
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install neovim
      sudo apt install -y python3 python3-dev python3-venv python3-pip
      #sudo add-apt-repository -y ppa:neovim-ppa/unstable && sudo apt update
      #sudo apt install -y neovim python3-dev python3-pip python3-venv
    elif [[ "$(./sys id)" == "mac" ]]; then
      brew install neovim python
    fi
  - nvim --headless "+Lazy! restore" +qa
