# Neovim + python + unzip

- link:
    ~/.config/nvim: nvim
    ~/.editorconfig: nvim/editorconfig

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed neovim python python-pip unzip
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install neovim python unzip
    elif [[ "$(./sys id)" == "fedora" ]]; then
      brew install neovim
      sudo dnf install -y python3 python3-devel python3-pip unzip
    elif [[ "$(./sys id)" == "mac" ]]; then
      brew install neovim python unzip
    fi
  - nvim --headless "+Lazy! restore" +qa
  - nvim --headless -c "lua require('nvim-treesitter').install({'lua','vim','vimdoc','python','java','c','cpp','html','css','javascript','typescript','tsx','sql','go','json','yaml','toml','bash','markdown','markdown_inline','beancount','typst'}):wait(60000)" -c "qa"


# - nvim --headless -c "MasonToolsInstallSync" -c "qa"

#sudo add-apt-repository -y ppa:neovim-ppa/unstable && sudo apt update
#sudo apt install -y neovim python3-dev python3-pip python3-venv
