
- link:
    ~/.config/opencode/:
      path: opencode/*
      glob: true

- shell:
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed opencode
    elif [[ "$(./sys id)" != "arch" ]]; then
      bun add -g opencode-ai
