
- link:
    ~/.local/bin/:
      path: scripts/*
      glob: true
      exclude: [scripts/utilities, scripts/archived]
    ~/.local/bin/sys: sys

- link:
    ~/.local/bin/:
      path: scripts/utilities/*
      glob: true

- shell: []
