
- link:
    ~/.config/starship.toml: tui/starship/starship.toml

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed starship
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install starship
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install starship
    fi
