
- link:
    ~/.config/tmux/tmux.conf: tmux/tmux.conf
    ~/.local/bin/:
      path: tmux/scripts/*
      glob: true

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed tmux git
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install tmux
      sudo apt install -y git
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install tmux git
    fi
  - |
    [ -d ~/.config/tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
    ~/.config/tmux/plugins/tpm/bin/install_plugins
