
- link:
    ~/.config/tmux/tmux.conf: tmux/tmux.conf
    ~/.local/bin/:
      path: tmux/scripts/*
      glob: true

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      #sudo pacman -S --noconfirm --needed tmux
      yay -S --noconfirm --needed --answerdiff None --answerclean None tmux-git
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install tmux
    elif [[ "$(./sys id)" == "fedora" ]]; then
      brew install tmux
    elif [[ "$(./sys id)" == "mac" ]]; then
      brew install tmux
    fi
  - |
    [ -d ~/.config/tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
    ~/.config/tmux/plugins/tpm/bin/install_plugins
