
- link:
    ~/.config/tmux/tmux.conf: tmux/tmux.conf
    ~/.local/bin/:
      path: tmux/scripts/*
      glob: true

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed tmux
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install tmux
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install tmux
    fi
