
- link:
    ~/.config/bat: tui/bat
    ~/.config/btop: tui/btop
    ~/.config/qalculate/qalc.cfg: tui/qalc/qalc.cfg
    ~/.config/cava/config: tui/cava/config
    ~/.config/fastfetch/config.jsonc:
      path: tui/fastfetch/config-arch.jsonc
      if: '[[ "$(./sys id)" == "arch" ]]'
    ~/.config/yazi:
      path: tui/yazi/*
      glob: true
- link:
    ~/.config/fastfetch/config.jsonc:
      path: tui/fastfetch/config-mac.jsonc
      if: '[[ "$(./sys id)" == "macos" ]]'

- link:
    ~/.config/fastfetch/config.jsonc:
      path: tui/fastfetch/config-ubuntu.jsonc
      if: '[[ "$(./sys id)" == "ubuntu" ]]'

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed bat yazi btop fastfetch cava gnuplot bc libqalculate
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install bat yazi btop fastfetch
      sudo apt install -y cava gnuplot bc qalc
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install bat yazi btop fastfetch cava gnuplot bc libqalculate
    fi
  - bat cache --build
  - cd ~/.config/yazi && ya pkg install

#Notes
#Cava does not work on macos without additional setup
