
- shell:
  - sudo pacman -S --noconfirm --needed qemu-full virt-manager virt-viewer dnsmasq
  - sudo systemctl enable --now libvirtd
  - sudo usermod -aG libvirt $USER #necessary to prevent polkit auth when opening virt-manager
#  - for f in virtualization/machines/*.xml; do sudo virsh define "$f"; done
#  Note - the above errors out due to some efi not being found
