
- link:
    ~/.config/yazi: tui/yazi

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed yazi
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      brew install yazi
    elif [[ "$(./sys id)" == "macos" ]]; then
      brew install yazi
    fi
