engines_as_actions = false

[[entries]]
default = true
name = "DuckDuckGo"
url = "https://duckduckgo.com/?q=%TERM%"

[[entries]]
name = "Google"
url = "https://www.google.com/search?q=%TERM%"

[[entries]]
name = "GitHub"
url = "https://github.com/search?q=%TERM%"

[[entries]]
name = "YouTube"
url = "https://www.youtube.com/results?search_query=%TERM%"

[[entries]]
name = "Wikipedia"
url = "https://en.wikipedia.org/wiki/Special:Search?search=%TERM%"

[[entries]]
name = "Arch Wiki"
url = "https://wiki.archlinux.org/index.php?search=%TERM%"
