
- link:
    ~/.config/rofi/:
      path: rofi/*
      glob: true
      exclude: [rofi/scripts]
    ~/.local/bin/:
      path: rofi/scripts/*
      glob: true

- shell:
  - sudo pacman -S --noconfirm --needed rofi
