
- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed xdg-utils ddcutil wl-clipboard gnome-keyring libsecret wtype reflector brightnessctl acpi fwupd 
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      echo "Please install"
    fi
