
- link:
    ~/.local/bin/:
      path: screensaver/scripts/*
      glob: true

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      sudo pacman -S --noconfirm --needed omarchy/python-terminaltexteffects
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      echo "not supported"
    fi
