
- shell:
  - sudo pacman -S --noconfirm --needed timeshift btrfs-progs grub-btrfs xorg-xhost
  - sudo rm -rf /etc/timeshift/timeshift.json
  - sudo cp -r timeshift/timeshift.json /etc/timeshift/timeshift.json
  - systemctl enable --now cronie.service
