
- shell:
  - sudo pacman -S --noconfirm --needed timeshift btrfs-progs xorg-xhost
  - sudo cp -r timeshift/timeshift.json /etc/timeshift/timeshift.json
  - sudo systemctl enable --now cronie.service

# Note - ideally the ESP should be at /boot/efi to allow timeshift to snapshot any kernels
