
- link: 
    ~/.config/vicinae/settings.json: vicinae/settings.json
    ~/.local/bin/vicinae-power.sh: vicinae/vicinae-power.sh

- shell:
  - |
    if [[ "$(./sys id)" == "arch" ]]; then
      yay -S --noconfirm --needed --answerdiff None --answerclean None vicinae-bin
    elif [[ "$(./sys id)" == "ubuntu" ]]; then
      echo "Not supported"
    elif [[ "$(./sys id)" == "fedora" ]]; then
      echo "Not supported"
    fi
  - systemctl --user enable vicinae
  - systemctl --user restart vicinae 2>/dev/null || true
