[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = "<C-n>"
run  = "shell -- ripdrag %s -x -a"
desc = "Drag n drop"

[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

#for macos quick look preview
[[mgr.prepend_keymap]]
on = "<C-p>"
for = "macos"
run = 'shell -- qlmanage -p "$@"' 

[[mgr.prepend_keymap]]
on   = "<C-p>"
for = "linux"
run  = 'shell -- sushi "$@"'
desc = "Large preview"

[[mgr.prepend_keymap]]
on = [ "m" ]
run = "plugin bookmarks save"
desc = "Save current position as a bookmark"

[[mgr.prepend_keymap]]
on = [ "'" ]
run = "plugin bookmarks jump"
desc = "Jump to a bookmark"

[[mgr.prepend_keymap]]
on = [ "b", "d" ]
run = "plugin bookmarks delete"
desc = "Delete a bookmark"

[[mgr.prepend_keymap]]
on  = "Y"
for = "linux"
run = [ 'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list', "yank" ]

[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd sftp://chocobo"
desc = "Go to chocobo server"

[[mgr.prepend_keymap]]
on   = "u"
run  = "plugin restore"
desc = "Restore last deleted files/folders"

[[mgr.prepend_keymap]]
on   = "R"
run  = "plugin recycle-bin"
desc = "Open Recycle Bin menu"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"
