
- link:
    ~/.local/share/applications/:
      path: apps/desktop-files/misc-apps/*
      glob: true
    ~/.local/share/icons/hicolor/scalable/apps/:
      path: apps/desktop-files/icons/*
      glob: true

- link:
    ~/.local/share/applications/:
      path: apps/desktop-files/hidden/*
      glob: true

#- link:
#    ~/.local/share/applications/:
#      path: apps/desktop-files/power-items/*
#      glob: true

- shell:
  - gtk-update-icon-cache -f -t ~/.local/share/icons/hicolor
  - update-desktop-database ~/.local/share/applications

- clean:
    ~/.local/share/icons/hicolor/:
      force: true
      recursive: true
    ~/.local/share/applications/:
      force: true
      recursive: true
